export const ONE_INTERNSHIP_DETAILS_REQUEST = "ONE_INTERNSHIP_DETAILS_REQUEST";
export const ONE_INTERNSHIP_DETAILS_SUCCESS = "ONE_INTERNSHIP_DETAILS_SUCCESS";
export const ONE_INTERNSHIP_DETAILS_FAILS = "ONE_INTERNSHIP_DETAILS_FAILS";

export const ALL_INTERNSHIPS__LIST_REQUEST = "ALL_INTERNSHIPS__LIST_REQUEST";
export const ALL_INTERNSHIPS__LIST_SUCCESS = "ALL_INTERNSHIPS__LIST_SUCCESS";
export const ALL_INTERNSHIPS__LIST_FAILS = "ALL_INTERNSHIPS__LIST_FAILS";

export const ALL_USER_INTERNSHIPS_REQUEST = "ALL_USER_INTERNSHIPS_REQUEST";
export const ALL_USER_INTERNSHIPS_SUCCESS = "ALL_USER_INTERNSHIPS_SUCCESS";
export const ALL_USER_INTERNSHIPS_FAILS = "ALL_USER_INTERNSHIPS_FAILS";

export const WEBDEV_INTERNSHIPS__LIST_REQUEST = "WEBDEV_INTERNSHIPS__LIST_REQUEST";
export const WEBDEV_INTERNSHIPS__LIST_SUCCESS = "WEBDEV_INTERNSHIPS__LIST_SUCCESS";
export const WEBDEV_INTERNSHIPS__LIST_FAILS = "WEBDEV_INTERNSHIPS__LIST_FAILS";

export const DESIGNING_INTERNSHIPS__LIST_REQUEST = "DESIGNING_INTERNSHIPS__LIST_REQUEST";
export const DESIGNING_INTERNSHIPS__LIST_SUCCESS = "DESIGNING_INTERNSHIPS__LIST_SUCCESS";
export const DESIGNING_INTERNSHIPS__LIST_FAILS = "DESIGNING_INTERNSHIPS__LIST_FAILS";

export const CONTENTWRITING_INTERNSHIPS__LIST_REQUEST = "CONTENTWRITING_INTERNSHIPS__LIST_REQUEST";
export const CONTENTWRITING_INTERNSHIPS__LIST_SUCCESS = "CONTENTWRITING_INTERNSHIPS__LIST_SUCCESS";
export const CONTENTWRITING_INTERNSHIPS__LIST_FAILS = "CONTENTWRITING_INTERNSHIPS__LIST_FAILS";

export const DIGITALMARKETING_INTERNSHIPS__LIST_REQUEST = "DIGITALMARKETING_INTERNSHIPS__LIST_REQUEST";
export const DIGITALMARKETING_INTERNSHIPS__LIST_SUCCESS = "DIGITALMARKETING_INTERNSHIPS__LIST_SUCCESS";
export const DIGITALMARKETING_INTERNSHIPS__LIST_FAILS = "DIGITALMARKETING_INTERNSHIPS__LIST_FAILS";

export const DATASCIENCE_INTERNSHIPS__LIST_REQUEST = "DATASCIENCE_INTERNSHIPS__LIST_REQUEST";
export const DATASCIENCE_INTERNSHIPS__LIST_SUCCESS = "DATASCIENCE_INTERNSHIPS__LIST_SUCCESS";
export const DATASCIENCE_INTERNSHIPS__LIST_FAILS = "DATASCIENCE_INTERNSHIPS__LIST_FAILS";

export const OTHER_INTERNSHIPS_LIST_REQUEST = "OTHER_INTERNSHIPS_LIST_REQUEST";
export const OTHER_INTERNSHIPS_LIST_SUCCESS = "OTHER_INTERNSHIPS_LIST_SUCCESS";
export const OTHER_INTERNSHIPS_LIST_FAILS = "OTHER_INTERNSHIPS_LIST_FAILS";

export const ALL_EMPLOYER_INTERNSHIPS_REQUEST = "ALL_EMPLOYER_INTERNSHIPS_REQUEST";
export const ALL_EMPLOYER_INTERNSHIPS_SUCCESS = "ALL_EMPLOYER_INTERNSHIPS_SUCCESS";
export const ALL_EMPLOYER_INTERNSHIPS_FAILS = "ALL_EMPLOYER_INTERNSHIPS_FAILS";

export const INTERNSHIP_CREATE_REQUEST = "INTERNSHIP_CREATE_REQUEST";
export const INTERNSHIP_CREATE_SUCCESS = "INTERNSHIP_CREATE_SUCCESS";
export const INTERNSHIP_CREATE_FAILS = "INTERNSHIP_CREATE_FAILS";