export const ONE_INTERNSHIP_DETAILS_REQUEST = "ONE_INTERNSHIP_DETAILS_REQUEST";
export const ONE_INTERNSHIP_DETAILS_SUCCESS = "ONE_INTERNSHIP_DETAILS_SUCCESS";
export const ONE_INTERNSHIP_DETAILS_FAILS = "ONE_INTERNSHIP_DETAILS_FAILS";

export const ALL_USER_INTERNSHIPS_REQUEST = "ALL_USER_INTERNSHIPS_REQUEST";
export const ALL_USER_INTERNSHIPS_SUCCESS = "ALL_USER_INTERNSHIPS_SUCCESS";
export const ALL_USER_INTERNSHIPS_FAILS = "ALL_USER_INTERNSHIPS_FAILS";

export const FRONTEND_INTERNSHIPS__LIST_REQUEST = "FRONTEND_INTERNSHIPS__LIST_REQUEST";
export const FRONTEND_INTERNSHIPS__LIST_SUCCESS = "FRONTEND_INTERNSHIPS__LIST_SUCCESS";
export const FRONTEND_INTERNSHIPS__LIST_FAILS = "FRONTEND_INTERNSHIPS__LIST_FAILS";

export const BACKEND_INTERNSHIPS__LIST_REQUEST = "BACKEND_INTERNSHIPS__LIST_REQUEST";
export const BACKEND_INTERNSHIPS__LIST_SUCCESS = "BACKEND_INTERNSHIPS__LIST_SUCCESS";
export const BACKEND_INTERNSHIPS__LIST_FAILS = "BACKEND_INTERNSHIPS__LIST_FAILS";

export const DESIGNING_INTERNSHIPS__LIST_REQUEST = "DESIGNING_INTERNSHIPS__LIST_REQUEST";
export const DESIGNING_INTERNSHIPS__LIST_SUCCESS = "DESIGNING_INTERNSHIPS__LIST_SUCCESS";
export const DESIGNING_INTERNSHIPS__LIST_FAILS = "DESIGNING_INTERNSHIPS__LIST_FAILS";

export const DATABASE_INTERNSHIPS__LIST_REQUEST = "DATABASE_INTERNSHIPS__LIST_REQUEST";
export const DATABASE_INTERNSHIPS__LIST_SUCCESS = "DATABASE_INTERNSHIPS__LIST_SUCCESS";
export const DATABASE_INTERNSHIPS__LIST_FAILS = "DATABASE_INTERNSHIPS__LIST_FAILS";

export const FULLSTACK_INTERNSHIPS__LIST_REQUEST = "FULLSTACK_INTERNSHIPS__LIST_REQUEST";
export const FULLSTACK_INTERNSHIPS__LIST_SUCCESS = "FULLSTACK_INTERNSHIPS__LIST_SUCCESS";
export const FULLSTACK_INTERNSHIPS__LIST_FAILS = "FULLSTACK_INTERNSHIPS__LIST_FAILS";

export const OTHER_INTERNSHIPS_LIST_REQUEST = "OTHER_INTERNSHIPS_LIST_REQUEST";
export const OTHER_INTERNSHIPS_LIST_SUCCESS = "OTHER_INTERNSHIPS_LIST_SUCCESS";
export const OTHER_INTERNSHIPS_LIST_FAILS = "OTHER_INTERNSHIPS_LIST_FAILS";

export const ALL_EMPLOYER_INTERNSHIPS_REQUEST = "ALL_EMPLOYER_INTERNSHIPS_REQUEST";
export const ALL_EMPLOYER_INTERNSHIPS_SUCCESS = "ALL_EMPLOYER_INTERNSHIPS_SUCCESS";
export const ALL_EMPLOYER_INTERNSHIPS_FAILS = "ALL_EMPLOYER_INTERNSHIPS_FAILS";

export const INTERNSHIP_CREATE_REQUEST = "INTERNSHIP_CREATE_REQUEST";
export const INTERNSHIP_CREATE_SUCCESS = "INTERNSHIP_CREATE_SUCCESS";
export const INTERNSHIP_CREATE_FAILS = "INTERNSHIP_CREATE_FAILS";